version: "3.9"

services:
  app:
    image: ghcr.io/algamja/algamja-api/app:${IMAGE_TAG}   # ← GitHub Actions가 sha로 덮어씁니다
    container_name: app
    expose:
      - "8080"
    env_file:
      - .env.app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: sh
    command: -c "trap exit TERM; while :; do sleep 12h & wait $!; certbot renew --webroot -w /var/www/certbot --deploy-hook 'nginx -s reload'; done"