spring:
  datasource:
    url: ENC(ZDpqWge75lwCaJv1jaPNNkx3tAzKi294wP7G31nhJK8Jd0kJvPDvgVQ0R99RxuoYI5WHKzOQLBclY2MiGsYXcl8WEPX5hA8EjCd+5ClhynvgZUUX9U2NCLZSUq2Che2t)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(kuV4NDaVfXCAy3oZAFZvsw==)
    password: ENC(eFBbprUYt6AEtXC9wqz5ebIg8oKK1bOr)

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ENC(kxlkqxO0NBEpaPla5xepuqS4lPRqowdcsA1tO0EDSmJ8ajStyuGPqPy892vtwLPY)
            client-secret: ENC(r3cFkFHBsImYzYvGwY+u2pNNVviwX3FELqdnJF2wV+3OpicqNlnU6AlraDJnGZk9)
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui
      display-request-duration: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump,env,loggers
  endpoint:
    health:
      show-details: always

server:
  port: 8080
  tomcat:
    threads:
      max: 50
      min-spare: 10

app:
  base-url: http://localhost:3000

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE