spring:
  profiles:
    active: local
    group:
      local:
        - local
        - local_oauth2
      dev:
        - dev
      prod:
        - prod
        - prod_oauth2

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

  jwt:
    secretKey: ENC(H/YIzvgutX1KSXRbpkyUqfaQG1qN9HgrCUFPWJQ0f2vSc+2FG6H3XIVyjcJ7TIQF3mFQOWlpIXqhAp2bp/tCwmfNxhKSHm5ynymmpiwMEo7txz6+PmCUdYYf5T92C5KowFk72d8SOb8naaVxiRWooXFUbQ8j+d9+DDRxuYRxWNB8sPVaq4BT8K9eyXBCiGCSCTnZ1YR3F5thHOfVxvQ4+5JM9ZQyr2ypedfFS694SnPsE1p+L2/uHMzx5uvw6EE0stIqRuk/2o8=)
    expirationTime: 1800000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}
    algorithm: ${JASYPT_ALGORITHM}

springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**