# EC2 환경용 설정
spring:
  profiles:
    active: ec2

# Selenium 관련 설정
selenium:
  chrome:
    # EC2에서는 항상 헤드리스 모드
    headless: true
    # Xvfb 디스플레이 설정
    display: ":99"
    # Chrome 바이너리 경로
    binary-path: "/usr/bin/google-chrome"
    # ChromeDriver 경로
    driver-path: "/usr/local/bin/chromedriver"
    # 추가 Chrome 옵션
    options:
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
      - "--disable-gpu"
      - "--disable-extensions"
      - "--disable-plugins"
      - "--disable-images"
      - "--disable-javascript"
      - "--window-size=1920,1080"
      - "--disable-blink-features=AutomationControlled"
      - "--disable-features=VizDisplayCompositor"
    # 실험적 옵션
    experimental-options:
      excludeSwitches: ["enable-automation"]
      useAutomationExtension: false

# 크롤링 설정
crawler:
  ably:
    # API 우선, 실패시 Selenium 백업
    fallback-to-selenium: true
    # 재시도 설정
    max-retries: 3
    retry-delay-ms: 2000
    # 타임아웃 설정
    selenium-timeout-seconds: 30
    page-load-delay-ms: 3000
    element-load-delay-ms: 1000
    
# 로깅 설정
logging:
  level:
    org.team_alilm.algamja.product.crawler: DEBUG
    org.openqa.selenium: WARN
    org.springframework.web.client: DEBUG
  pattern:
    file: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: "/var/log/alilm/crawler.log"