spring:
  profiles:
    active: local
    group:
      local:
        - local
      dev:
        - dev
    include: oauth2

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: true

  jwt:
    secretKey: ENC(XHzc4j5aQ9QBZsvGZxTRRzSyKU1wfRFruDDgZZKMrVLVDuR0kzpK+b2jc9t+r3Flj++7Jn3z3s16PCGWBgEpKCthC8FEzQGJcpINWNs452+MuIyzON3wMmr7WqfJhDyevB8xGLeWHurz2ROwV9p1gHFZoCuMa/yrC++W4iU8lRRk2Wkr9G2H67inPkXqyt1I)
    expirationTime: 1800000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}
    algorithm: ${JASYPT_ALGORITHM}