spring:
  config:
    activate:
      on-profile: oauth2

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ENC(NbBUj89oVS3cZPjyqpY3IJ1aeP6APd4Shu8TKGdFhCQS7MF1Gj9U7ARmYDW+Tmr1)
            client-secret: ENC(stc5I/Npc0dAqzq0kJCCUVZWvr56YljGhsc05zY2BLvaTuymqQJjeY6QSo5w3ZsT)
            redirect-uri:
              - http://localhost:8080/login/oauth2/code/kakao
              - https://alilm.store/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
              - gender
              - birthyear
              - phone_number
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id