spring:
  profiles:
    group:
      local:
        - local
      prod:
        - prod
    default: local

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

  quartz:
    job-store-type: jdbc

  jwt:
    secretKey: ENC(H/YIzvgutX1KSXRbpkyUqfaQG1qN9HgrCUFPWJQ0f2vSc+2FG6H3XIVyjcJ7TIQF3mFQOWlpIXqhAp2bp/tCwmfNxhKSHm5ynymmpiwMEo7txz6+PmCUdYYf5T92C5KowFk72d8SOb8naaVxiRWooXFUbQ8j+d9+DDRxuYRxWNB8sPVaq4BT8K9eyXBCiGCSCTnZ1YR3F5thHOfVxvQ4+5JM9ZQyr2ypedfFS694SnPsE1p+L2/uHMzx5uvw6EE0stIqRuk/2o8=)
    expirationTime: 2592000000

  mail:
    from: Team Alilm
    subject: 안녕하세요 Team Alilm입니다.
    username: ENC(zZZR0mstC9GJj3o2n9uNo4fSIxBtFkzivLzYAAo5Vb8=)
    password: ENC(8hyiyfxLieKE3paHstTxKOyqKgKSNjVnTPXU4YvLPRs=)
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000r

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ENC(JFUTm4eV3OhN/ieNVz1nZKEw0Jyxf8CWw/talXBFwTz+wz/uB54IsbZWRgB7oPbw)
            client-secret: ENC(f2dlB5aO+N/SLAomV8175UXz/54n7Wh7qjI4OXo+u43PaOa/VAwxMitWDYW1PmJf)
            redirect-uri: https://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}
    algorithm: ${JASYPT_ALGORITHM}

springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**

webhook:
  slack:
    url: ENC(ZaEdZrZmyxJlGPIk0zgsxBR7D2K8h/F5nqyHyEDh2XIsn0mpi4+UE/jL7zvDAyiewcDDIsd1xc+HspuW3FWd84mebkC4k0H0vXciOaARckAz7xgu/c6+1kRy0hDbLLXP)
