spring:
  profiles:
    group:
      local:
        - local
      prod:
        - prod


  quartz:
    job-store-type: jdbc


  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

    open-in-view: true

  jwt:
    secretKey: ENC(H/YIzvgutX1KSXRbpkyUqfaQG1qN9HgrCUFPWJQ0f2vSc+2FG6H3XIVyjcJ7TIQF3mFQOWlpIXqhAp2bp/tCwmfNxhKSHm5ynymmpiwMEo7txz6+PmCUdYYf5T92C5KowFk72d8SOb8naaVxiRWooXFUbQ8j+d9+DDRxuYRxWNB8sPVaq4BT8K9eyXBCiGCSCTnZ1YR3F5thHOfVxvQ4+5JM9ZQyr2ypedfFS694SnPsE1p+L2/uHMzx5uvw6EE0stIqRuk/2o8=)
    expirationTime: 86400000

  mail:
    from: Team Alilm
    subject: 안녕하세요 Team Alilm입니다.
    username: ENC(zZZR0mstC9GJj3o2n9uNo4fSIxBtFkzivLzYAAo5Vb8=)
    password: ENC(8hyiyfxLieKE3paHstTxKOyqKgKSNjVnTPXU4YvLPRs=)
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000r

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}
    algorithm: ${JASYPT_ALGORITHM}

springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**

webhook:
  slack:
    url: ENC(66oIt8AFhAxu4Kt9kV5SIvPbb+QALCAbBJOQAOoftXdYaWp+yAa5H20WZTlGoyeo26OB8UAq8GxkiSlkyWZwUsR+eLr/ZLhPk0lde5A9MLFSZi6/DT5cIiAtOd+el6CP)