spring:
  quartz:
    job-store-type: jdbc
    soldout-job-interval-minutes: 5
    member-count-job-interval-minutes: 5

  cloud:
    aws:
      credentials:
        access-key: ENC(KE/Ro8r1NbGMPsOESPM5KeY7Jkk5f8cXGBZnHjIw6aI=)
        secret-key: ENC(XVIV5AuAv7dBtD/076Vgl+LjKjOqTnWPftROOtnBT/lWUCuzbqll0v118UJbqZLN1di9zhffyCM=)
        region:
          static: ap-northeast-2

server:
  port: 8081