spring:
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yml
      - optional:classpath:application-security-${spring.profiles.active}.yml
  profiles:
    active: local

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}
    algorithm: ${JASYPT_ALGORITHM}

server:
  port: 8082

logging:
  config: classpath:logback-spring.xml