spring:
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yml
      - optional:classpath:application-security-${spring.profiles.active}.yml
  profiles:
    active: local

server:
  port: 8082