spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(YImIZ27t2aagGM4kNvBPf1s8CIfPHVIrkz511rCcYyQE1uoDwkynAIRwT86QulMHIsscSh0TH8YPhHrSi8vQ9u8+yUNp2jRNN7BaEsisG0nn3lla5mOBo3jMBWOwV5uF)
    username: ENC(R1FpK3IkTBlUqe6UGu9ASA==)
    password: ENC(Xg2/I1uWGCs6SKi2H21oNAazYU4qObrp)