spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:local
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true

    open-in-view: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

webhook:
  slack:
    url: ENC(ZaEdZrZmyxJlGPIk0zgsxBR7D2K8h/F5nqyHyEDh2XIsn0mpi4+UE/jL7zvDAyiewcDDIsd1xc+HspuW3FWd84mebkC4k0H0vXciOaARckAz7xgu/c6+1kRy0hDbLLXP)