spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(FouU6thkEz8xyLqbwBbp34yFWFXpK+cF0RSzgVvFJGbASaRRkVvOSUVdb8pxOa3uw6W1XA8MPrm7ukf+ZFcy6eXZEw6gqP5JglxurG9ElEXUBNfToh/yOQ==)
    username: ENC(R1FpK3IkTBlUqe6UGu9ASA==)
    password: ENC(Xg2/I1uWGCs6SKi2H21oNAazYU4qObrp)

webhook:
  slack:
    url: ENC(66oIt8AFhAxu4Kt9kV5SIvPbb+QALCAbBJOQAOoftXdYaWp+yAa5H20WZTlGoyeo26OB8UAq8GxkiSlkyWZwUsR+eLr/ZLhPk0lde5A9MLFSZi6/DT5cIiAtOd+el6CP)
