spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(FFhQuos3vg7hqH0nRunAu+soeQFzV8ld6eW73y4oHYqFdOD90rV0BLe9DnUiXiXGpQFLIiTbeXzuq4VFiS/2EbG6nA9e293rE28JcxRboae7Z92TuRAMjH3L0BtKCjtu)
    username: ENC(R1FpK3IkTBlUqe6UGu9ASA==)
    password: ENC(Xg2/I1uWGCs6SKi2H21oNAazYU4qObrp)

webhook:
  slack:
    url: ENC(66oIt8AFhAxu4Kt9kV5SIvPbb+QALCAbBJOQAOoftXdYaWp+yAa5H20WZTlGoyeo26OB8UAq8GxkiSlkyWZwUsR+eLr/ZLhPk0lde5A9MLFSZi6/DT5cIiAtOd+el6CP)
