spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

  quartz:
    job-store-type: jdbc
    job-interval-minutes: 1

  jwt:
    secretKey: ENC(H/YIzvgutX1KSXRbpkyUqfaQG1qN9HgrCUFPWJQ0f2vSc+2FG6H3XIVyjcJ7TIQF3mFQOWlpIXqhAp2bp/tCwmfNxhKSHm5ynymmpiwMEo7txz6+PmCUdYYf5T92C5KowFk72d8SOb8naaVxiRWooXFUbQ8j+d9+DDRxuYRxWNB8sPVaq4BT8K9eyXBCiGCSCTnZ1YR3F5thHOfVxvQ4+5JM9ZQyr2ypedfFS694SnPsE1p+L2/uHMzx5uvw6EE0stIqRuk/2o8=)
    expirationTime: 2592000000

  mail:
    from: Team Alilm
    username: ENC(zZZR0mstC9GJj3o2n9uNo4fSIxBtFkzivLzYAAo5Vb8=)
    password: ENC(8hyiyfxLieKE3paHstTxKOyqKgKSNjVnTPXU4YvLPRs=)
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}
    algorithm: ${JASYPT_ALGORITHM}

springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**