name: Detect Changes and Deploy API

on:
  pull_request:
    branches:
      - dev  # 배포할 브랜치 설정

jobs:
  detect-api:
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.detect-api.outputs.api_changed }}
      core_changed: ${{ steps.detect-api.outputs.core_changed }}
      security_changed: ${{ steps.detect-api.outputs.security_changed }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 커밋 이력 가져오기

      - name: Detect changes in API server
        id: detect-api
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'api/'; then
            echo "API server has changed."
            echo "api_changed=true" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          else
            echo "No changes in API server."
            echo "api_changed=false" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          fi
          
          if git diff --name-only HEAD^ HEAD | grep -q 'core/'; then
            echo "Core module has changed."
            echo "core_changed=true" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          else
            echo "No changes in core module."
            echo "core_changed=false" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          fi
          
          if git diff --name-only HEAD^ HEAD | grep -q 'security/'; then
            echo "Security module has changed."
            echo "security_changed=true" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          else
            echo "No changes in security module."
            echo "security_changed=false" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          fi

  deploy-api:
    runs-on: ubuntu-latest
    needs: detect-api
    if: ${{ needs.detect-api.outputs.api_changed == 'true' || needs.detect-api.outputs.core_changed == 'true' || needs.detect-api.outputs.security_changed == 'true' }}  # outputs 사용

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Firebase service key
        run: |
          mkdir -p core/src/main/resources/firebase
          echo ${{ secrets.FIREBASE_SECRET_KEY }} | base64 -d > core/src/main/resources/firebase/FirebaseSecretKey.json

      - name: Build with Gradle Wrapper
        run: ./gradlew :api:build

