name: Detect Changes and Build WORKER

on:
  pull_request:
    branches:
      - dev  # 배포할 브랜치 설정

jobs:
  detect-worker:
    runs-on: ubuntu-latest
    outputs:
      worker_changed: ${{ steps.detect-worker.outputs.worker_changed }}  # outputs로 설정
      core_changed: ${{ steps.detect-worker.outputs.core_changed }}  # API 서버와 공유하는 core 모듈 변경 여부

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 커밋 이력 가져오기

      - name: Detect changes in WORKER server
        id: detect-worker
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'worker/'; then
            echo "WORKER server has changed."
            echo "worker_changed=true" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          else
            echo "No changes in WORKER server."
            echo "worker_changed=false" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          fi
          
          if git diff --name-only HEAD^ HEAD | grep -q 'core/'; then
            echo "Core module has changed."
            echo "core_changed=true" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          else
            echo "No changes in core module."
            echo "core_changed=false" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          fi

  build-worker:
    runs-on: ubuntu-latest
    needs: detect-worker
    if: ${{ needs.detect-worker.outputs.worker_changed == 'true' || needs.detect-worker.outputs.core_changed == 'true' }}  # outputs 사용

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Firebase service key
        run: |
          mkdir -p core/src/main/resources/firebase
          echo ${{ secrets.FIREBASE_SECRET_KEY }} | base64 -d > core/src/main/resources/firebase/FirebaseSecretKey.json

      - name: Build with Gradle Wrapper
        run: ./gradlew :worker:build
