name: Detect Changes and Build CRAWLER

on:
  pull_request:
    branches:
      - dev  # 배포할 브랜치 설정

jobs:
  detect-crawler:
    runs-on: ubuntu-latest
    outputs:
      crawler_changed: ${{ steps.detect-crawler.outputs.crawler_changed }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes in CRAWLER and Core
        id: detect-crawler
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'crawler/'; then
            echo "crawler_changed=true" >> $GITHUB_OUTPUT
          fi

  build-crawler:
    runs-on: ubuntu-latest
    needs: detect-crawler
    if: ${{ needs.detect-crawler.outputs.crawler_changed == 'true' }}  # outputs 사용

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle Wrapper
        run: ./gradlew :crawler:build
