name: Detect Changes and Build

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    name: Detect Changes in Each Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 커밋 이력 가져오기

      - name: Detect changes in API server
        id: detect-api
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'api/'; then
            echo "API server has changed."
            echo "api-changed=true" >> $GITHUB_ENV
          else
            echo "No changes in API server."
            echo "api-changed=false" >> $GITHUB_ENV
          fi

      - name: Detect changes in Worker server
        id: detect-worker
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'worker/'; then
            echo "Worker server has changed."
            echo "worker-changed=true" >> $GITHUB_ENV
          else
            echo "No changes in Worker server."
            echo "worker-changed=false" >> $GITHUB_ENV
          fi

      - name: Detect changes in Proxy server
        id: detect-proxy
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'proxy/'; then
            echo "Proxy server has changed."
            echo "proxy-changed=true" >> $GITHUB_ENV
          else
            echo "No changes in Proxy server."
            echo "proxy-changed=false" >> $GITHUB_ENV
          fi
