name: Detect Changes and Build

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 커밋 이력 가져오기

      - name: Detect changes in API server
        id: detect-api
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'api/'; then
            echo "API server has changed."
            echo "api_changed=true" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          else
            echo "No changes in API server."
            echo "api_changed=false" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          fi

      - name: Detect changes in Worker server
        id: detect-worker
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'worker/'; then
            echo "Worker server has changed."
            echo "worker_changed=true" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          else
            echo "No changes in Worker server."
            echo "worker_changed=false" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          fi

      - name: Detect changes in Proxy server
        id: detect-proxy
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'proxy/'; then
            echo "Proxy server has changed."
            echo "proxy_changed=true" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          else
            echo "No changes in Proxy server."
            echo "proxy_changed=false" >> $GITHUB_OUTPUT  # 아웃풋으로 설정
          fi

      - name: Echo outputs
        run: |
          echo "API Changed: ${{ steps.detect-api.outputs.api_changed }}"
          echo "Worker Changed: ${{ steps.detect-worker.outputs.worker_changed }}"
          echo "Proxy Changed: ${{ steps.detect-proxy.outputs.proxy_changed }}"
