name: Detect Changes and Build

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    name: Detect Changes in Each Server
    runs-on: ubuntu-latest
    outputs:
      api-changed: ${{ steps.detect-api.outputs.api-changed }}
      worker-changed: ${{ steps.detect-worker.outputs.worker-changed }}
      proxy-changed: ${{ steps.detect-proxy.outputs.proxy-changed }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 커밋 이력 가져오기

      - name: Detect changes in API server
        id: detect-api
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'api/'; then
            echo "API server has changed."
            echo "api-changed=true" >> $GITHUB_ENV
            echo "api-changed=true" >> $GITHUB_OUTPUT  # Set output using Environment File
          else
            echo "No changes in API server."
            echo "api-changed=false" >> $GITHUB_ENV
            echo "api-changed=false" >> $GITHUB_OUTPUT  # Set output using Environment File
          fi

      - name: Detect changes in Worker server
        id: detect-worker
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'worker/'; then
            echo "Worker server has changed."
            echo "worker-changed=true" >> $GITHUB_ENV
            echo "worker-changed=true" >> $GITHUB_OUTPUT  # Set output using Environment File
          else
            echo "No changes in Worker server."
            echo "worker-changed=false" >> $GITHUB_ENV
            echo "worker-changed=false" >> $GITHUB_OUTPUT  # Set output using Environment File
          fi

      - name: Detect changes in Proxy server
        id: detect-proxy
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'proxy/'; then
            echo "Proxy server has changed."
            echo "proxy-changed=true" >> $GITHUB_ENV
            echo "proxy-changed=true" >> $GITHUB_OUTPUT  # Set output using Environment File
          else
            echo "No changes in Proxy server."
            echo "proxy-changed=false" >> $GITHUB_ENV
            echo "proxy-changed=false" >> $GITHUB_OUTPUT  # Set output using Environment File
          fi
